rebaseMergeAllowed: false
squashMergeAllowed: true
mergeCommitAllowed: false
deleteBranchOnMerge: true
branchProtectionRules:
- pattern: main
  isAdminEnforced: false
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: false
  requiresStrictStatusChecks: false
  requiredStatusCheckContexts:
    - Validate PR title
    - release-dry-run

    - Linter (cli)
    - Unit Tests (cli)

    - SQLPolicyTest (plugins/source/aws, postgres:10, 1.18, ubuntu-latest)
    - Check Generated Code for Drift (aws)
    - Linter (plugins/source/aws)
    - Unit Tests (plugins/source/aws)
    - Lint Provider Doc (plugins/source/aws)

    - SQLPolicyTest (plugins/source/azure, postgres:10, 1.18, ubuntu-latest)
    - Check Generated Code for Drift (azure)
    - Linter (plugins/source/azure)
    - Unit Tests (plugins/source/azure)
    - Lint Provider Doc (plugins/source/azure)

    - Check Generated Code for Drift (cloudflare)
    - Linter (plugins/source/cloudflare)
    - Unit Tests (plugins/source/cloudflare)
    - Lint Provider Doc (plugins/source/cloudflare)

    - Linter (plugins/source/digitalocean)
    - Unit Tests (plugins/source/digitalocean)
    - Lint Provider Doc (plugins/source/digitalocean)

    - Linter (plugins/source/fuzz)
    - Unit Tests (plugins/source/fuzz)

    - SQLPolicyTest (plugins/source/gcp, postgres:10, 1.18, ubuntu-latest)
    - Check Generated Code for Drift (gcp)
    - Linter (plugins/source/gcp)
    - Unit Tests (plugins/source/gcp)
    - Lint Provider Doc (plugins/source/gcp)

    - Check Generated Code for Drift (github)
    - Linter (plugins/source/github)
    - Unit Tests (plugins/source/github)
    - Lint Provider Doc (plugins/source/github)

    - Linter (plugins/source/k8s)
    - Unit Tests (plugins/source/k8s)
    - Lint Provider Doc (plugins/source/k8s)

    - Linter (plugins/source/okta)
    - Unit Tests (plugins/source/okta)
    - Lint Provider Doc (plugins/source/okta)

    - Linter (plugins/source/terraform)
    - Unit Tests (plugins/source/terraform)
    - Lint Provider Doc (plugins/source/terraform)
