name: Approve Vercel Website Build

on:
  pull_request:
    paths:
      - "**/*"
      - "!website/**"
    branches:
      - main

jobs:
  set-vercel-to-success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          status: success
          name: "Vercel â€“ cloudquery-web"