name: Destination Plugin Azure Blob Storage Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "plugins/destination/azblob/**"
      - ".github/workflows/dest_azblob.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/destination/azblob/**"
      - ".github/workflows/dest_azblob.yml"

jobs:
  plugins-destination-azblob:
    timeout-minutes: 30
    name: "plugins/destination/azblob"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/destination/azblob
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: plugins/destination/azblob/go.mod
          cache: true
          cache-dependency-path: plugins/destination/azblob/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.6
          working-directory: plugins/destination/azblob
          args: "--config ../../.golangci.yml"
      - name: gen
        if: github.event_name == 'pull_request'
        run: make gen
      - name: Fail if generation updated files
        if: github.event_name == 'pull_request'
        run: test "$(git status -s | wc -l)" -eq 0 || (git status -s; exit 1)
      - name: Build
        run: go build .
      - name: Test azblob plugin
        run: make test
        env:
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  