name: Destination Plugin MySQL Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "plugins/destination/mysql/**"
      - ".github/workflows/dest_mysql.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/destination/mysql/**"
      - ".github/workflows/dest_mysql.yml"

jobs:
  plugins-destination-mysql:
    timeout-minutes: 30
    name: "plugins/destination/mysql"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/destination/mysql
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: plugins/destination/mysql/go.mod
          cache: true
          cache-dependency-path: plugins/destination/mysql/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.55.2
          working-directory: plugins/destination/mysql
          args: "--config ../../.golangci.yml"
      - name: gen
        if: github.event_name == 'pull_request'
        run: make gen
      - name: Fail if generation updated files
        if: github.event_name == 'pull_request'
        run: test "$(git status -s | wc -l)" -eq 0 || (git status -s; exit 1)
      - name: Build
        run: go build .
      # We don't use services as we need to pass additional arguments to the container
      - name: Spin up MySQL
        run: |
          docker run --platform linux/amd64 -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=test -e MYSQL_DATABASE=cloudquery -d mysql:8.0 --innodb_log_file_size=512M --innodb_strict_mode=0
          sudo apt update && sudo apt install wait-for-it -y
          wait-for-it -h localhost -p 3306
      - name: Test MySQL
        run: make test
  validate-config-ui:
    timeout-minutes: 15
    if: github.event_name == 'pull_request'
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/destination/mysql
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: plugins/destination/mysql/go.mod
          cache: true
          cache-dependency-path: plugins/destination/mysql/go.sum
      - name: Build
        run: go build .
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: "plugins/destination/mysql/cloud-config-ui/package-lock.json"
      - name: Install dependencies
        working-directory: "plugins/destination/mysql/cloud-config-ui"
        run: npm ci
      - name: Install dotenv
        run: npm install dotenv-cli -g
      - name: Install Playwright
        working-directory: "plugins/destination/mysql/cloud-config-ui"
        run: npx playwright install --with-deps
      - name: Build config UI
        working-directory: "plugins/destination/mysql/cloud-config-ui"
        run: REACT_APP_USE_CLOUD_APP_MOCK=true npm run build
        env:
          REACT_APP_PLUGIN_TEAM: cloudquery
          REACT_APP_PLUGIN_KIND: destination
          REACT_APP_PLUGIN_NAME: mysql
          REACT_APP_PLUGIN_VERSION: development
      - name: Run E2E tests and generate configs
        working-directory: "plugins/destination/mysql/cloud-config-ui"
        run: E2E_TESTS_GENERATE_CONFIG=true npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: config-ui-e2e-testsplaywright
          path: |
            "plugins/destination/mysql/cloud-config-ui/playwright-report/"
          retention-days: 7
          if-no-files-found: error
      - name: Run unit tests
        working-directory: "plugins/destination/mysql/cloud-config-ui"
        run: npm run test

  deploy:
    if: github.event.action != 'closed' && github.event_name == 'pull_request' && !startsWith(github.head_ref, 'release')
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    defaults:
      run:
        working-directory: ./plugins/destination/mysql/cloud-config-ui
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-deploy
      cancel-in-progress: false # to make sure that old Vercel deployments are deleted

    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          DEPLOYMENT_URL=$(vercel --token $VERCEL_TOKEN)
          echo "Deployed to: $DEPLOYMENT_URL"
          echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_ENV
          ALIAS_DEPLOYMENT_BASE_URL=plugin-destination-mysql-cloud-ui-${{ github.event.pull_request.number }}.vercel.app
          ALIAS_DEPLOYMENT_URL=https://$ALIAS_DEPLOYMENT_BASE_URL
          vercel --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID alias $DEPLOYMENT_URL $ALIAS_DEPLOYMENT_BASE_URL
          echo "Alias deployed to: $ALIAS_DEPLOYMENT_URL"
          echo "ALIAS_DEPLOYMENT_URL=$ALIAS_DEPLOYMENT_URL" >> $GITHUB_ENV
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          token: ${{ secrets.GH_CQ_BOT }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "cq-bot"
          body-includes: "MySQL Cloud UI deployed to Vercel:"

      - name: Delete Previous Vercel Deployment (if comment with URL exists)
        if: steps.find-comment.outputs.comment-id != ''
        run: |
          echo "Comment found:"
          echo "${{ steps.find-comment.outputs.comment-body }}"
          PREVIOUS_DEPLOYMENT_URL=$(echo "${{ steps.find-comment.outputs.comment-body }}" | awk '/Unique Vercel deployment URL:/ {getline; print $1}')
          echo "Previous deployment URL: $PREVIOUS_DEPLOYMENT_URL"
          if vercel rm "$PREVIOUS_DEPLOYMENT_URL" --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID --yes; then
            echo "Deployment $PREVIOUS_DEPLOYMENT_URL was successfully deleted."
          else
            echo "Failed to delete deployment $PREVIOUS_DEPLOYMENT_URL. It may not exist or there was an error."
          fi
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GH_CQ_BOT }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ðŸš€ MySQL Cloud UI deployed to Vercel:
            ${{ env.ALIAS_DEPLOYMENT_URL }}
            You can also check out this plugin in action at:
            https://cloud.cloudquery.io/teams/cloudquery-test/destinations/create?plugin-cloud-ui=cloudquery|destination|mysql|${{ env.ALIAS_DEPLOYMENT_URL }}
            Unique Vercel deployment URL:
            ${{ env.DEPLOYMENT_URL }}
          edit-mode: replace
