name: Destination Plugin Azure Blob Storage Workflow

on:
  pull_request:
    paths:
      - "plugins/destination/azblob/**"
      - ".github/workflows/dest_azblob.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/destination/azblob/**"
      - ".github/workflows/dest_azblob.yml"

jobs:
  plugins-destination-azblob:
    timeout-minutes: 30
    name: "plugins/destination/azblob"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/destination/azblob
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: plugins/destination/azblob/go.mod
          cache: true
          cache-dependency-path: plugins/destination/azblob/go.sum
      - name: golangci-lint
        uses: cloudquery/golangci-lint-action@master
        with:
          version: v1.50.1
          working-directory: plugins/destination/azblob
          args: "--config ../../.golangci.yml"
          skip-pkg-cache: true
          skip-build-cache: true
      - name: Get dependencies
        run: go get -t -d ./...
      - name: Build
        run: go build .
      - name: Test azblob plugin
        run: make test
        env:
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  validate-release:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - name: Checkout
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-1.19.4-release-cache-${{ hashFiles('plugins/destination/azblob/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-1.19.4-release-cache-plugins-destination-azblob
      - name: Set up Go
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        uses: actions/setup-go@v3
        with:
          go-version-file: plugins/destination/azblob/go.mod
      - name: Install GoReleaser
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser-pro
          version: latest
          install-only: true
      - name: Run GoReleaser Dry-Run
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        run: goreleaser release --snapshot --rm-dist --skip-validate --skip-publish --skip-sign -f ./plugins/destination/azblob/.goreleaser.yaml
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
