name: Destination Plugin Test Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "plugins/destination/test/**"
      - ".github/workflows/dest_test.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/destination/test/**"
      - ".github/workflows/dest_test.yml"

permissions:
  contents: read

jobs:
  plugins-destination-test:
    timeout-minutes: 30
    name: "plugins/destination/test"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/destination/test
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        id: setup-go
        uses: actions/setup-go@v6
        with:
          go-version-file: plugins/destination/test/go.mod
          cache: false
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ steps.setup-go.outputs.go-version }}-test-destination-test-${{ hashFiles('plugins/destination/test/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ steps.setup-go.outputs.go-version }}-test-destination-test-
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10.1
          working-directory: plugins/destination/test
          args: "--config ../../.golangci.yml"
      - name: Build
        run: go build .
      - name: Test
        run: make test
  