name: Destination Plugin Snowflake Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "plugins/destination/snowflake/**"
      - ".github/workflows/dest_snowflake.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/destination/snowflake/**"
      - ".github/workflows/dest_snowflake.yml"

jobs:
  plugins-destination-snowflake:
    timeout-minutes: 30
    name: "plugins/destination/snowflake"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/destination/snowflake
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: plugins/destination/snowflake/go.mod
          cache: true
          cache-dependency-path: plugins/destination/snowflake/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.6
          working-directory: plugins/destination/snowflake
          args: "--config ../../.golangci.yml"
      - name: gen
        if: github.event_name == 'pull_request'
        run: make gen
      - name: Fail if generation updated files
        if: github.event_name == 'pull_request'
        run: test "$(git status -s | wc -l)" -eq 0 || (git status -s; exit 1)
      - name: Build
        run: go build .
      - name: Test
        run: make test
        env: # Or as an environment variable
          SNOW_TEST_DSN: ${{ secrets.SNOW_TEST_DSN }}
  