name: Destination Plugin GCS Workflow

on:
  pull_request:
    paths:
      - "plugins/destination/gcs/**"
      - ".github/workflows/dest_gcs.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/destination/gcs/**"
      - ".github/workflows/dest_gcs.yml"

jobs:
  plugins-destination-gcs:
    timeout-minutes: 30
    name: "plugins/destination/gcs"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/destination/gcs
    permissions:
      id-token: 'write' # This required for OIDC
      contents: 'read' # This is required for actions/checkout@v3
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/151868820337/locations/global/workloadIdentityPools/integration-test-pool/providers/integration-test-provider'
          service_account: 'integration-service-account@cq-integration-tests.iam.gserviceaccount.com'
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: plugins/destination/gcs/go.mod
          cache: true
          cache-dependency-path: plugins/destination/gcs/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          working-directory: plugins/destination/gcs
          args: "--config ../../.golangci.yml"
          skip-pkg-cache: true
          skip-build-cache: true
      - name: Get dependencies
        run: go get -t -d ./...
      - name: Build
        run: go build .
      - name: Test file plugin
        run: make test
  validate-release:
    if:   startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
    uses: ./.github/workflows/validate_release.yml
    with:
      path: plugins/destination/gcs
