name: Destination Plugin Postgresql Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "plugins/destination/postgresql/**"
      - ".github/workflows/dest_postgresql.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/destination/postgresql/**"
      - ".github/workflows/dest_postgresql.yml"

permissions:
  contents: read

jobs:
  plugins-destination-postgresql:
    timeout-minutes: 30
    name: "plugins/destination/postgresql"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/destination/postgresql
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: plugins/destination/postgresql/go.mod
          cache: true
          cache-dependency-path: plugins/destination/postgresql/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          working-directory: plugins/destination/postgresql
          args: "--config ../../.golangci.yml"
      - name: gen
        if: github.event_name == 'pull_request'
        run: make gen
      - name: Fail if generation updated files
        if: github.event_name == 'pull_request'
        run: test "$(git status -s | wc -l)" -eq 0 || (git status -s; exit 1)
      - name: Build
        run: go build .
      - name: Test PG
        run: make test
      - name: Test CockroachDB
        run: make test-cockroachdb

  validate-fips:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/destination/postgresql
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-1.25.5-validate-plugin-fips-cache-${{ hashFiles('plugins/destination/postgresql/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-1.25.5-validate-plugin-fips-cache-destination-postgresql

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: plugins/destination/postgresql/go.mod
          cache: false

      - name: Run package command
        env:
          GOFLAGS: "-tags=fipsEnabled"
        run: |
          rm -rf docs/tables.md
          go run main_fips.go package -m "chore: Test FIPS" "v1.0.0" .

      - name: Unzip package artifacts
        run: |
          unzip -o dist/plugin-postgresql-v1.0.0-linux-amd64.zip
          chmod +x plugin-postgresql-v1.0.0-linux-amd64
          ./plugin-postgresql-v1.0.0-linux-amd64 --version 2>&1 | grep -E 'FIPS enabled: true'
