name: Destination Plugin Kinesis Firehose Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "plugins/destination/firehose/**"
      - ".github/workflows/dest_firehose.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/destination/firehose/**"
      - ".github/workflows/dest_firehose.yml"

permissions:
  contents: read

jobs:
  plugins-destination-firehose:
    timeout-minutes: 30
    name: "plugins/destination/firehose"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/destination/firehose
    permissions:
      id-token: write
      contents: read # This is required for actions/checkout@v3
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
     
      - name: Set up Go 1.x
        id: setup-go
        uses: actions/setup-go@v6
        with:
          go-version-file: plugins/destination/firehose/go.mod
          cache: false
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ steps.setup-go.outputs.go-version }}-test-destination-firehose-${{ hashFiles('plugins/destination/firehose/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ steps.setup-go.outputs.go-version }}-test-destination-firehose-
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10.1
          working-directory: plugins/destination/firehose
          args: "--config ../../.golangci.yml"
      - name: gen
        if: github.event_name == 'pull_request'
        run: make gen
      - name: Fail if generation updated files
        if: github.event_name == 'pull_request'
        run: test "$(git status -s | wc -l)" -eq 0 || (git status -s; exit 1)
      - name: Build
        run: go build .
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-to-assume: arn:aws:iam::615713231484:role/destination-s3
      #     aws-region: us-east-1        
      # - name: Test firehose plugin
      #   run: make test
  
