name: Destination Plugin Test Workflow

on:
  pull_request:
    paths:
      - "plugins/destination/test/**"
      - ".github/workflows/dest_test.yml"
  push:
    paths:
      - "plugins/destination/test/**"
      - ".github/workflows/dest_test.yml"
    branches:
      - main

defaults:
  run:
    working-directory: ./plugins/destination/test

jobs:
  plugins-destination-test:
    name: "plugins/destination/test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: plugins/destination/test/go.mod
          cache: true
          cache-dependency-path: plugins/destination/test/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          working-directory: plugins/destination/test
          args: "--config ../../.golangci.yml"
      - name: Get dependencies
        run: go get -t -d ./...
      - name: Build
        run: go build .
      - name: Test
        run: go test ./...
