name: Destination Plugin MySQL Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "plugins/destination/mysql/**"
      - ".github/workflows/dest_mysql.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/destination/mysql/**"
      - ".github/workflows/dest_mysql.yml"

jobs:
  plugins-destination-mysql:
    timeout-minutes: 30
    name: "plugins/destination/mysql"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/destination/mysql
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: plugins/destination/mysql/go.mod
          cache: true
          cache-dependency-path: plugins/destination/mysql/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.55.2
          working-directory: plugins/destination/mysql
          args: "--config ../../.golangci.yml"
          skip-pkg-cache: true
          skip-build-cache: true
      - name: gen
        if: github.event_name == 'pull_request'
        run: make gen
      - name: Fail if generation updated files
        if: github.event_name == 'pull_request'
        run: test "$(git status -s | wc -l)" -eq 0 || (git status -s; exit 1)
      - name: Build
        run: go build .
      # We don't use services as we need to pass additional arguments to the container
      - name: Spin up MySQL
        run: |
          docker run --platform linux/amd64 -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=test -e MYSQL_DATABASE=cloudquery -d mysql:8.0 --innodb_log_file_size=512M --innodb_strict_mode=0
          sudo apt update && sudo apt install wait-for-it -y
          wait-for-it -h localhost -p 3306
      - name: Test MySQL
        run: make test
  