name: Lint Markdown files

on:
  pull_request:
    paths:
      - ".github/workflows/lint_markdown.yml"
      - "**.md"
      - "**.mdx"

jobs:
  lint-grammar:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - run: |
          venv="$HOME/.local/share/venv"
          python3 -m venv "$venv"
          echo "$venv/bin" >> $GITHUB_PATH
      - name: Vale
        uses: errata-ai/vale-action@3a4769d4af5f9498e586fb41abc72bbca594b400
        with:
          vale_flags: "--glob=!{website/pages/blog/podcast-software-engineer-daily.md,**/CHANGELOG.md,**/docs/tables/README.md,**/docs/_licenses.md,plugins/source/test/docs/tables/*.md,.github/styles/proselint/README.md,**/v1-migration.md,website/pages/docs/plugins/sources/*/tables.md,plugins/source/*/docs/policies.md,**/tables/**/*,website/pages/case-studies/*.mdx,cli/internal/docs/testdata/*.md}"
          filter_mode: nofilter
          fail_on_error: true
          version: '3.0.3'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  lint-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .markdownlint.yaml
          ignore_files: "{website/pages/blog/podcast-software-engineer-daily.md,**/CHANGELOG.md,**/docs/tables/README.md,plugins/source/test/docs/tables/*.md,website/pages/docs/reference/cli/**,website/tables/**/*}"
