name: Report missing tables

on:
  # Using pull_request works on forked PRs too. This is safe since we don't checkout the PR code (we only use the diff)
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened
jobs:
  missing-tables:
    if: startsWith(github.head_ref, 'release-please--branches--main--components')
    defaults:
      run:
        working-directory: scripts/missing_tables
    timeout-minutes: 15
    runs-on: ubuntu-latest
    outputs:
      breaking: ${{ steps.breaking.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: scripts/missing_tables/go.mod
          cache: true
          cache-dependency-path: scripts/missing_tables/go.sum
      - name: Get missing tables
        id: missing-tables
        run: |
          missing_tables=$(go run main.go)
          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$missing_tables" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Find Comment
        uses: peter-evans/find-comment@025109652c8a93d074bfe8b64ff81f011cac8928
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '### This PR has missing tables'
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@267c0605edbbc0183ed9973a6ce2d1a158d96027
        if: steps.missing-tables.outputs.result != ''
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### This PR has missing tables

            ${{steps.missing-tables.outputs.result}}
          edit-mode: replace
      - name: Delete comment
        if: steps.find-comment.outputs.comment-id != '' && steps.missing-tables.outputs.result == ''
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ steps.find-comment.outputs.comment-id }}
            })
  
