name: Source Plugin DigitalOcean Workflow

on:
  pull_request:
    paths:
      - "plugins/source/digitalocean/**"
      - ".github/workflows/source_digitalocean.yml"

defaults:
  run:
    working-directory: ./plugins/source/digitalocean

jobs:
  plugins-source-digitalocean:
    name: "plugins/source/digitalocean"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: plugins/source/digitalocean/go.mod
          cache: true
          cache-dependency-path: plugins/source/digitalocean/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          working-directory: plugins/source/digitalocean
          args: "--config ../../.golangci.yml"
      - name: Get dependencies
        run: go get -t -d ./...
      - name: Build
        run: go build .
      - name: Test
        run: make test
      - name: gen-docs
        run: make gen-docs
      - name: Fail if docs are changed
        run: test "$(git status -s ./docs/tables | wc -l)" -eq 0
