name: Source Plugin Test Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "plugins/source/test/**"
      - ".github/workflows/source_test.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/source/test/**"
      - ".github/workflows/source_test.yml"

jobs:
  plugins-source-test:
    timeout-minutes: 30
    name: "plugins/source/test"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/source/test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: plugins/source/test/go.mod
          cache: true
          cache-dependency-path: plugins/source/test/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          working-directory: plugins/source/test
          args: "--config ../../.golangci.yml"
      - name: Setup CloudQuery
        if: github.event_name == 'pull_request'
        uses: cloudquery/setup-cloudquery@v4
        with:
          version: v6.23.0
      - name: gen
        if: github.event_name == 'pull_request'
        run: make gen
      - name: Fail if generation updated files
        if: github.event_name == 'pull_request'
        run: test "$(git status -s | wc -l)" -eq 0 || (git status -s; exit 1)
      - name: Build
        run: go build .
      - name: Test
        run: make test
  validate-fips:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gythialy/golang-cross:1.24.4
    defaults:
      run:
        working-directory: ./plugins/source/test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # https://github.com/actions/checkout/issues/2031
      - name: Set safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-1.24.4-validate-plugin-fips-cache-${{ hashFiles('plugins/source/test/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-1.24.4-validate-plugin-fips-cache-source-test

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: plugins/source/test/go.mod
          cache: false

      - name: Run package command
        env:
          GOEXPERIMENT: "boringcrypto"
        run: |
          rm -rf docs/tables.md
          go run main.go package -m "chore: Test FIPS" "v1.0.0" .

      - name: Unzip package artifacts
        run: |
          unzip -o dist/plugin-test-v1.0.0-linux-amd64.zip
          chmod +x plugin-test-v1.0.0-linux-amd64
          ./plugin-test-v1.0.0-linux-amd64 --version

      - name: Validate FIPS build
        run: |
          go tool nm plugin-test-v1.0.0-linux-amd64 | grep -E 'sig.FIPSOnly|sig.BoringCrypto'