name: Source Plugin Heroku Workflow

on:
  pull_request:
    paths:
      - "plugins/source/heroku/**"
      - ".github/workflows/source_heroku.yml"
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./plugins/source/heroku

jobs:
  plugins-source-heroku:
    name: "plugins/source/heroku"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: plugins/source/heroku/go.mod
          cache: true
          cache-dependency-path: plugins/source/heroku/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          working-directory: plugins/source/heroku
          args: "--config ../../.golangci.yml"
      - name: Get dependencies
        run: go get -t -d ./...
      - name: Build
        run: go build .
      - name: Test
        run: go test ./...
