name: Source Plugin MySQL Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "plugins/source/mysql/**"
      - ".github/workflows/source_mysql.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/source/mysql/**"
      - ".github/workflows/source_mysql.yml"

jobs:
  plugins-source-mysql:
    timeout-minutes: 30
    name: "plugins/source/mysql"
    runs-on: large-ubuntu-monorepo
    defaults:
      run:
        working-directory: ./plugins/source/mysql
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: plugins/source/mysql/go.mod
          cache: true
          cache-dependency-path: plugins/source/mysql/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
          working-directory: plugins/source/mysql
          args: "--config ../../.golangci.yml"
          skip-pkg-cache: true
          skip-build-cache: true
      - name: Build
        run: go build .
      # We don't use services as we need to pass additional arguments to the container
      - name: Spin up MySQL
        run: |
          docker run --platform linux/amd64 -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=test -e MYSQL_DATABASE=cloudquery -d mysql:5.7 --innodb_log_file_size=512M --innodb_strict_mode=0
          sudo apt update && sudo apt install wait-for-it -y
          wait-for-it -h localhost -p 3306
      - name: Test mysql
        run: make test
  validate-release:
    timeout-minutes: 30
    runs-on: large-ubuntu-monorepo
    env:
      CGO_ENABLED: 0
    steps:
      - name: Checkout
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-1.21.0-release-cache-${{ hashFiles('plugins/source/mysql/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-1.21.0-release-cache-plugins-source-mysql
      - name: Set up Go
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        uses: actions/setup-go@v3
        with:
          go-version-file: plugins/source/mysql/go.mod
      - name: Install GoReleaser
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser-pro
          version: latest
          install-only: true
      - name: Run GoReleaser Dry-Run
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        run: goreleaser release --snapshot --clean --skip-validate --skip-publish --skip-sign -f ./plugins/source/mysql/.goreleaser.yaml
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
