name: Source Plugin Postgresql Workflow

on:
  pull_request:
    paths:
      - "plugins/source/postgresql/**"
      - ".github/workflows/source_postgresql.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/source/postgresql/**"
      - ".github/workflows/source_postgresql.yml"

jobs:
  plugins-source-postgresql:
    timeout-minutes: 30
    name: "plugins/source/postgresql"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/source/postgresql
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: plugins/source/postgresql/go.mod
          cache: true
          cache-dependency-path: plugins/source/postgresql/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          working-directory: plugins/source/postgresql
          args: "--config ../../.golangci.yml"
          skip-pkg-cache: true
          skip-build-cache: true
      - name: Get dependencies
        run: go get -t -d ./...
      - name: Build
        run: go build .
      # github actions built-in service doesn't support logical replication yet (as far as I was able to find out)
      - name: Spin up PostgreSQL with logical replication
        run: |
          docker run -p 5432:5432 -e POSTGRES_PASSWORD=pass -d postgres:11 -c "wal_level=logical"
          sudo apt update && sudo apt install wait-for-it -y
          wait-for-it -h localhost -p 5432
      - name: Test PostgreSQL
        run: make test
  validate-release:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - name: Checkout
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-1.19.5-release-cache-${{ hashFiles('plugins/source/postgresql/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-1.19.5-release-cache-plugins-source-postgresql
      - name: Set up Go
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        uses: actions/setup-go@v3
        with:
          go-version-file: plugins/source/postgresql/go.mod
      - name: Install GoReleaser
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser-pro
          version: latest
          install-only: true
      - name: Run GoReleaser Dry-Run
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        run: goreleaser release --snapshot --clean --skip-validate --skip-publish --skip-sign -f ./plugins/source/postgresql/.goreleaser.yaml
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
