name: Transformer Plugin JSON Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "plugins/transformer/jsonflattener/**"
      - ".github/workflows/transf_jsonflattener.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/transformer/jsonflattener/**"
      - ".github/workflows/transf_jsonflattener.yml"

permissions:
  contents: read

jobs:
  plugins-transformer-json:
    timeout-minutes: 30
    name: "plugins/transformer/jsonflattener"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/transformer/jsonflattener
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        id: setup-go
        uses: actions/setup-go@v6
        with:
          go-version-file: plugins/transformer/jsonflattener/go.mod
          cache: false
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ steps.setup-go.outputs.go-version }}-test-transformer-jsonflattener-${{ hashFiles('plugins/transformer/jsonflattener/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ steps.setup-go.outputs.go-version }}-test-transformer-jsonflattener-
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10.1
          working-directory: plugins/transformer/jsonflattener
          args: "--config ../../.golangci.yml"
      - name: Build
        run: go build .
      - name: Test
        run: make test
  